#!/usr/bin/perl -w

use strict;
use warnings;

use Debconf::Client::ConfModule qw(:all);

title("APC UPS Reporter Configuration");

my @s;
@s = input("critical", "app-apc-reporter/backend");
@s = go();
my $site = get("app-apc-reporter/backend");
fset("app-apc-reporter/backend", "changed", "true");

@s = input("critical", "app-apc-reporter/cronpattern");
@s = go();
my $cron = get("app-apc-reporter/cronpattern");
fset("app-apc-reporter/cronpattern", "changed", "true");

__END__


. /usr/share/debconf/confmodule

db_version 2.0
db_capb backup

db_beginblock
db_input medium debconf/frontend || true
db_input medium debconf/priority || true
db_endblock
db_go || true